# Nexus Plugin Configuration File
# ------------------------------------

# Linguagens suportadas (en-us,pt-br)
# Supported languages (en-us,pt-br)
lang: pt-br

# Se o servidor está em expurgo, permite roubo de reliquia se verdadeiro
# If the server is in purge, allow relic stealing if true
expurgo: false

# Lista de recursos para desativar durante o expurgo
# List of resources to disable during purge
recursos:
  troca: true
  loja: true
  missao: true
  #Segundos
  #Seconds
  missaoCooldown: 300
  tpa: true
  #money
  tpacost: 100.0
  bauMorte: true
  enderchest: true
  #money
  enderchestcost: 5000.0
  moneyName: "moly"
  procurados: true
  # Ativa ou desativa a relíquia aleatória para novos jogadores.
  # Se ativado, um novo jogador recebeu uma relíquia não utilizada ao entrar pela primeira vez.
  nexus_onjoin: false

# Limite de reliquias que um jogador pode ter, se o jogador passar disso ele é derrotado e é deixado com apenas 1 reliquia
# Limit of relics that a player can have, if the player exceeds this he is defeated and is left with only 1 relic
limite: 4

# Level maximo que as reliquias podem evoluir, se definido como 1 ou menor desabilida o level maximo
# Maximum level that relics can evolve, if set to 1 or lower, it disables the maximum level
levelMax: 20

# Quantidade de xp que precisa para evoluir, o calculo é xp*level
# Amount of xp you need to evolve, the calculation is xp*level
xptolevel: 7

# Registro das reliquias, quando algum jogador possui fica registrado o UUID dele
# Registration of relics, when a player has one, his UUID is registered
nexus:
  guerreiro: ""
  ceifador: ""
  vida: ""
  mares: ""
  barbaro: ""
  fazendeiro: ""
  espiao: ""
  arqueiro: ""
  cacador: ""
  tempestade: ""
  mineiro: ""
  fenix: ""
  protetor: ""
  hulk: ""
  sculk: ""
  pescador: ""
  flash: ""
  mago: ""
  ladrao: ""
  domador: ""
  cozinheiro: ""
  construtor: ""
  abissal: ""
  cronosombra: ""
  assassino: ""
  frostis: ""
  necromante: ""
  alquimista: ""
  golem: ""
  dragao: ""

# Registro de jogadores com permissões limitadas de OP
# Registering players with limited OP permissions
op-players: {}

# Registro de jogadores procurados
# Register of wanted players
procurados: {}

# Configuração de jogadores e cargos
# Player and role configuration
players: {}

# Configuração de ranks/cargos
# Rank/Role configuration
ranks:
  - "Membro"
# Cargos cores
# Positions colors
cargos:
  Membro: "#ffffff"