# Nexus Plugin Configuration File
# ------------------------------------

# Linguagens suportadas (en-us,pt-br)
# Supported languages (en-us,pt-br)
lang: pt-br

# Se o servidor está em expurgo, permite roubo de reliquia se verdadeiro
# If the server is in purge, allow relic stealing if true
expurgo: false

# Lista de comandos para desativar durante o expurgo
# List of commands to disable during purge
expurgo_comandos_desativados:
  - "trocar"
  - "loja"
  - "missoes"
  - "banco"
  - "team"

# Limite de reliquias que um jogador pode ter, se o jogador passar disso ele é derrotado e é deixado com apenas 1 reliquia
# Limit of relics that a player can have, if the player exceeds this he is defeated and is left with only 1 relic
limite: 3

# Level maximo que as reliquias podem evoluir, se definido como 1 ou menor desabilida o level maximo
# Maximum level that relics can evolve, if set to 1 or lower, it disables the maximum level
levelMax: 20

# Quantidade de xp que precisa para evoluir, o calculo é xp*level
# Amount of xp you need to evolve, the calculation is xp*level
xptolevel: 7

# Ativa ou desativa o sistema de renascimento com pagamento.
# Se desativado, a tela de morte padrão do Minecraft será usada.
sistema_renascimento_ativado: true

# Ativa ou desativa a relíquia aleatória para novos jogadores.
# Se ativado, um novo jogador recebeu uma relíquia não utilizada ao entrar pela primeira vez.
dar_reliquia_ao_entrar: true

# Registro das reliquias, quando algum jogador possui fica registrado o UUID dele
# Registration of relics, when a player has one, his UUID is registered
nexus:
  guerreiro: ""
  ceifador: ""
  vida: ""
  mares: ""
  barbaro: ""
  fazendeiro: ""
  espiao: ""
  arqueiro: ""
  cacador: ""
  tempestade: ""
  mineiro: ""
  fenix: ""
  protetor: ""
  hulk: ""
  sculk: ""
  pescador: ""
  flash: ""
  mago: ""
  ladrao: ""
  domador: ""
  cozinheiro: ""
  construtor: ""
  abissal: ""
  cronosombra: ""
  assassino: ""
  frostis: ""
  necromante: ""
  alquimista: ""
  golem: ""
  dragao: ""

# Configurações do Banco Central do Nexus
nexus_central_bank:
  saldo: 25000000.0

# REGISTRO DE SALDOS DOS JOGADORES (NOVO)
player_balances: {}

# REGISTRO DE EMPRÉSTIMOS (NOVO)
emprestimos: {}

# REGISTRO DE HISTÓRICO DE TRANSAÇÕES (NOVO)
historico: {}

# Registro de jogadores com permissões limitadas de OP
op-players: {}

# Registro de jogadores procurados
procurados: {}

# Configuração de jogadores e cargos
players: {}