name: Reliquias_Nexus
version: 'v1.0.8'
main: org.dantesys.reliquiasNexus.ReliquiasNexus
api-version: '1.21'
authors: [ Dantesys ]
softdepend: [ floodgate ]
commands:
  nexus:
    description: Comando principal do Nexus
    usage: /nexus [subcomando]
  nexusAdmin:
    description: Comandos de operador do Nexus
    usage: /nexusAdmin [subcomando]
  ec:
    description: Abrir ender chest
    usage: /ec
  tpa:
    description: Sistema de teleporte
    usage: /tpa

permissions:
  reliquiasnexus.opzim:
    description: Acesso aos comandos administrativos do Nexus
    default: false
  reliquiasnexus.admin:
    description: Acesso aos comandos administrativos do Nexus
    default: op
  reliquiasnexus.vip:
    description: Status VIP no servidor
    default: false
  reliquiasnexus.playerlist:
    description: Ver player list personalizada
    default: true
  reliquiasnexus.command.nexus:
    description: Usar comando /nexus
    default: true
  reliquiasnexus.command.nexusAdmin:
    description: Usar comando /nexusAdmin
    default: op