package org.dantesys.reliquiasNexus.books;

import net.kyori.adventure.text.Component;
import net.kyori.adventure.text.format.NamedTextColor;
import net.kyori.adventure.text.format.TextDecoration;
import org.bukkit.Material;
import org.bukkit.inventory.ItemStack;
import org.bukkit.inventory.meta.BookMeta;

import java.util.ArrayList;
import java.util.List;

public class NexusStoryBook {

    public static ItemStack createBook() {
        ItemStack book = new ItemStack(Material.WRITTEN_BOOK);
        BookMeta meta = (BookMeta) book.getItemMeta();

        meta.title(Component.text("§6Nexus Story").color(NamedTextColor.GOLD));
        meta.author(Component.text("§7O Ancião").color(NamedTextColor.GRAY));

        List<Component> pages = new ArrayList<>();

        // História do Servidor (7 Páginas)
        pages.add(Component.text("§6📜 História do Nexus\n\n§7Símbolo antigo do Nexus: ⌘✦⚙✦⌘\n\n" +
                "No princípio, o Nexus era apenas uma sombra de mundo, um espaço vazio entre eras, onde o tempo e a matéria se entrelaçavam de formas que ninguém compreendia. Povos antigos narravam que seres invisíveis moldavam o solo, desenhavam rios e erguiam montanhas com gestos silenciosos. A origem do Nexus é desconhecida; alguns dizem que ele nasceu de um sonho coletivo de civilizações que jamais se viram, outros afirmam que sempre existiu, esperando por aqueles dignos de explorá-lo. Os registros mais antigos falam de templos invisíveis, rios que mudam de curso com a vontade de forças misteriosas e criaturas que desaparecem ao serem observadas."));

        pages.add(Component.text("§6Página 2\n\n" +
                "Os povos antigos, que chamavam a si mesmos de Guardiões do Éter, deixaram inscrições em pedras negras e monumentos em ruínas, mas mesmo esses registros são ambíguos. Contam histórias de relíquias com poderes incompreensíveis: armas que falam, amuletos que enxergam a alma e artefatos que controlam elementos naturais. Cada relíquia é um fragmento do próprio Nexus, mas ninguém jamais soube como ou por que elas surgiram. A verdade permanece oculta, escondida em labirintos de pedra, cavernas abissais e florestas que desafiam mapas modernos."));

        pages.add(Component.text("§6Página 3\n\n" +
                "Exploradores que tentaram descobrir a origem do Nexus relatam fenômenos impossíveis: florestas que se movem, rios que desaparecem durante o dia e reaparecem à noite, sombras que seguem mesmo na luz plena. Lendas falam de encontros com seres que nunca falam, apenas observam, como se o próprio Nexus fosse consciente. Cada passo dado pelos intrusos parece registrar-se em memórias antigas, que só os olhos atentos conseguem perceber. É um lugar de mistérios, onde passado, presente e futuro coexistem, confundindo até os mais sábios."));

        pages.add(Component.text("§6Página 4\n\n" +
                "Dentro do Nexus, existiram povos que construíram cidades e fortalezas, algumas elevadas acima das nuvens, outras enterradas em cavernas eternas. Eles cultivavam magia, ciência e arte, mas desapareceram sem deixar rastros, como se tivessem sido engolidos pelo próprio mundo que ajudaram a formar. Relíquias antigas surgiram desses povos, carregando pedaços de sua essência. Algumas relíquias eram pacíficas, outras letais; todas eram guardadas por enigmas e provas que testavam coragem, inteligência e coração."));

        pages.add(Component.text("§6Página 5\n\n" +
                "Dizem que o Nexus possui consciências ocultas, chamadas de Sentinelas, que observam cada tentativa de exploração. Elas não atacam, mas testam, confundem e guiam os dignos. É comum que viajantes encontrem símbolos antigos gravados em rochas e árvores, sinais de passagem ou advertências. Cada símbolo é único, carregado de energia do mundo primordial. Alguns se movem com a luz do sol; outros desaparecem à noite. Tudo dentro do Nexus parece ter vida própria, como se o mundo fosse consciente e moldado por vontades que ninguém pode decifrar totalmente."));

        pages.add(Component.text("§6Página 6\n\n" +
                "Ao longo dos séculos, histórias surgiram sobre heróis que dominaram partes do Nexus e suas relíquias, alcançando feitos que parecem impossíveis hoje. Entretanto, essas histórias vêm sempre com um aviso: nada é gratuito, nada é eterno, e tudo que se toca deixa uma marca que nem mesmo o tempo consegue apagar. A própria natureza do Nexus ensina que curiosidade e coragem devem ser equilibradas com respeito e sabedoria, pois ultrapassar limites sem preparo leva à perdição."));

        pages.add(Component.text("§6Página 7\n\n" +
                "Hoje, o Nexus é tanto lenda quanto realidade. Poucos ousam explorá-lo, mas aqueles que o fazem encontram relíquias, símbolos antigos e ecos de civilizações perdidas. Cada canto guarda mistérios, enigmas e perigos. Ninguém sabe ao certo como ele surgiu, e talvez nunca saibamos. Mas uma verdade permanece: o Nexus é vivo, consciente, e seus segredos esperam pacientemente por aqueles que tiverem coragem suficiente para decifrá-los. Cada passo, cada descoberta, cada relíquia encontrada é apenas uma peça do quebra-cabeça eterno que é o Nexus."));

        // Histórias das Relíquias (4 Páginas por Relíquia)
        addRelicStory(pages, "Guerreiro", "⚔️", "A Relíquia do Guerreiro nasceu no coração de batalhas ancestrais, forjada em aço negro e imbuída da coragem de mil heróis esquecidos. Povos antigos protegiam templos de pedra onde a lâmina descansava, e apenas os dignos podiam tocá-la. Cada golpe da lâmina carrega ecos de lutas passadas, lembrando que força sem honra é vaidade.", "Exploradores contam que, ao empunhar a lâmina, passos de guerreiros invisíveis ecoam ao redor. A lâmina não apenas corta: ela lembra, observa, e ensina. Aliados sentem inspiração; inimigos, medo. Quem a domina aprende que a batalha é tanto física quanto espiritual, e cada ação deixa marcas no próprio Nexus.", "Somente os puros de espírito e fortes de coração conseguem manejar o Guerreiro sem se perder nas vozes ancestrais. Muitos tentaram e falharam. A lâmina é memória, legado e julgamento, e quem a carrega torna-se parte de uma história viva que atravessa eras.", "Pontos fortes: Dano e resistência inigualáveis, aumenta a velocidade de combate.\nPontos fracos: Lento fora do combate, vulnerável a ataques de longa distância.");
        addRelicStory(pages, "Ceifador", "☠️", "Envolta em névoa, a Relíquia do Ceifador é antiga como o próprio Nexus. Surgiu em eclipses, quando sombras cobriram aldeias inteiras. Quem a toca sente a fragilidade da vida e ouve sussurros de almas que partiram.", "Exploradores relatam sombras que se movem e olhos que observam, como se a relíquia estivesse viva. Ela testa seu portador: coragem, sabedoria e respeito pela vida são exigências. Muitos desaparecem sem deixar rastro, transformados em ecos que ainda rondam templos esquecidos.", "Aqueles que sobrevivem dizem que o Ceifador não corrompe pelo poder, mas pelo medo e ganância. Ele lembra que a vida é efêmera e a morte inevitável. Só quem compreende essa verdade retorna das sombras com alma intacta.", "Pontos fortes: Dano devastador, pode ceifar várias almas de uma vez, portador se torna ágil.\nPontos fracos: Baixa defesa, vulnerável a inimigos mais fortes, exige sacrifícios.");
        addRelicStory(pages, "Vida", "💠", "Nascida no coração de uma floresta eterna, a Relíquia da Vida brilha com uma luz suave que pulsa como um coração. Quem a toca sente a vida ao redor: o bater de corações, o murmúrio das plantas, o vento carregando memórias antigas.", "Povos antigos ofereciam tributos, respeitando os ciclos naturais. Exploradores modernos sentem o equilíbrio instável: a vida que dá também exige cuidado. Ganância e imprudência trazem doenças e morte, lembrando que a Vida não se submete a caprichos.", "Somente os pacientes, compassivos e respeitosos conseguem dominá-la. A Vida é dom e julgamento; quem entende seu valor pode curar e proteger, enquanto os imprudentes se perdem entre sombras esquecidas.", "Pontos fortes: Cura rápida, alta defesa e vida, pode reviver aliados.\nPontos fracos: Baixo dano de ataque, portador se torna o alvo principal.");
        addRelicStory(pages, "Mares", "🌊", "Forjada nas profundezas, a Relíquia dos Mares guarda segredos de oceanos que ninguém jamais viu. Criaturas abissais a protegem, e ondas invisíveis dançam ao redor de quem a segura.", "Navegadores contam histórias de tempestades e calmarias, de águas respondendo à intenção do portador. Quem respeita recebe o poder sobre correntes, ventos e criaturas; quem desrespeita desaparece nas profundezas.", "Lendas falam de capitães conectados com cada criatura e cada onda, mas também de outros engolidos pelo mar. É dom e provação, desafiando coragem e coração de quem ousa dominá-la.", "Pontos fortes: Controle sobre a água, habilidades de mobilidade e ataques à distância.\nPontos fracos: Vulnerável a ataques de fogo, ineficaz em terra firme.");
        addRelicStory(pages, "Bárbaro", "🪓", "Moldada nas florestas ancestrais, a Relíquia do Bárbaro carrega instinto e liberdade selvagem. Guerreiros que jamais se submeteram a reis deixaram sua essência nela.", "Portadores sentem fúria antiga, gritos de tribos extintas e ecos de florestas esquecidas. A relíquia desperta força, instinto e estratégia selvagem.", "Quem não controla a fúria sucumbe. Quem equilibra instinto e razão torna-se lenda viva, ligado à liberdade do Nexus.", "Pontos fortes: Força bruta, ataques poderosos em área.\nPontos fracos: Baixa defesa, portador se torna irracional se não controlar a fúria.");
        addRelicStory(pages, "Fazendeiro", "🌾", "Nascida de terras férteis, a Relíquia do Fazendeiro simboliza prosperidade. Povos antigos consideravam-na sagrada, pois a colheita é vida.", "Exploradores sentem a terra crescer à sua volta, mas a relíquia exige respeito. Ganância leva a colheitas murchas e animais doentes.", "Somente quem respeita os ciclos naturais domina seu poder. É dom e lição, lembrando que a vida não pode ser manipulada sem cuidado.", "Pontos fortes: Aumenta a colheita, cura através de alimentos.\nPontos fracos: Ineficaz em combate, passivo.");
        addRelicStory(pages, "Espião", "👁", "A Relíquia do Espião observa em silêncio, revelando segredos invisíveis.", "Portadores enxergam além de paredes e mentiras, descobrindo o que deveria permanecer oculto.", "Mas o peso do conhecimento enlouquece. Quem a usa demais se perde em memórias que não lhe pertencem.", "Pontos fortes: Habilidades de furtividade, revelação de inimigos.\nPontos fracos: Vulnerável em combate direto, pode causar loucura.");
        addRelicStory(pages, "Arqueiro", "🏹", "Criada do vento e da distância, a Relíquia do Arqueiro garante precisão sobrenatural.", "Cada flecha encontra seu destino, mesmo além do controle do portador.", "Somente paciência e foco permitem seu uso seguro.", "Pontos fortes: Precisão perfeita, ataques de longa distância.\nPontos fracos: Ineficaz em combate corpo a corpo.");
        addRelicStory(pages, "Caçador", "🐺", "Forjada sob a lua cheia, a Relíquia do Caçador desperta instintos selvagens.", "Portadores caminham com lobos invisíveis, guiados por sentidos aguçados.", "Lobos exigem sacrifício; quem ignora as regras desaparece.", "Pontos fortes: Sentidos aguçados, pode rastrear e caçar inimigos.\nPontos fracos: Vulnerável em ambientes urbanos, lobos podem trair o portador.");
        addRelicStory(pages, "Tempestade", "⛈", "Nascida do coração de tempestades eternas, sua fúria domina trovões e ventos.", "O céu responde a cada gesto do portador.", "Somente quem aceita a força da natureza sobrevive ao seu poder.", "Pontos fortes: Controle do clima, ataques elétricos e de vento.\nPontos fracos: Ineficaz em cavernas, depende do clima.");
        addRelicStory(pages, "Mineiro", "⛏", "Forjada no centro da terra, revela tesouros escondidos.", "Cada veia de minério responde à presença do portador.", "Mas a ganância cobra seu preço, lembrando que nada é de graça.", "Pontos fortes: Velocidade de mineração, revelação de minérios.\nPontos fracos: Ineficaz em combate, dependente de minérios.");
        addRelicStory(pages, "Fênix", "🔥", "Criada do fogo e das cinzas, nunca se apaga.", "Sua chama destrói e renova, trazendo renascimento e dor.", "Quem a ergue sente morte e renascimento como parte de si.", "Pontos fortes: Imortalidade, renascimento.\nPontos fracos: Vulnerável a água e gelo, pode ser destruído pelo próprio fogo.");
        addRelicStory(pages, "Protetor", "🛡", "Forjada para proteger os fracos, pesada como seu dever.", "O portador se torna bastião contra o mal.", "Quem a desrespeita é esmagado por sua própria proteção.", "Pontos fortes: Alta defesa, invencibilidade temporária.\nPontos fracos: Baixa mobilidade, portador se torna um alvo.");
        addRelicStory(pages, "Hulk", "💪", "Força concentrada, descontrolada e poderosa.", "Golpes ecoam no chão e no coração dos inimigos.", "Quem a domina deve conter a fúria ou será consumido.", "Pontos fortes: Força bruta, ataques poderosos.\nPontos fracos: Baixa inteligência, portador se torna um ser irracional.");
        addRelicStory(pages, "Sculk", "🦠", "Nascida do silêncio das profundezas, capta cada som.", "Seus ecos seguem o portador.", "Quem tenta enganá-la é encontrado pelas sombras.", "Pontos fortes: Habilidades sensoriais, revelação de inimigos.\nPontos fracos: Ineficaz em combate, vulnerável a barulhos.");
        addRelicStory(pages, "Pescador", "🎣", "Linha lançada no vazio trouxe esta relíquia, capaz de capturar mais que peixes.", "Destino e memórias podem ser fisgados.", "Quem a usa imprudentemente desaparece no mar.", "Pontos fortes: Captura de itens raros, controle sobre a água.\nPontos fracos: Ineficaz em combate, dependente da água.");
        addRelicStory(pages, "Flash", "⚡", "Relíquia da velocidade, mais rápida que a luz.", "O tempo se curva; segundos parecem eternidade.", "O corpo mortal paga o preço da pressa.", "Pontos fortes: Super velocidade, agilidade.\nPontos fracos: Vulnerável a ataques de área, portador pode se cansar rapidamente.");
        addRelicStory(pages, "Mago", "✨", "Formada de estrelas cadentes, palavras moldam o ar.", "O portador sente o cosmos fluindo através de si.", "Mas até as estrelas morrem, levando aqueles que tentam dominá-las.", "Pontos fortes: Magia de ataque e defesa, pode controlar o tempo.\nPontos fracos: Baixa defesa, portador se torna o alvo principal.");
        addRelicStory(pages, "Ladrão", "🗡", "Pequena, discreta e mortal, rouba mais que ouro.", "Memórias e identidades desaparecem sem aviso.", "Quem a possui pode se tornar fantasma de si mesmo.", "Pontos fortes: Furtividade, roubo de itens.\nPontos fracos: Vulnerável em combate direto, pode se tornar um ser sem identidade.");
        addRelicStory(pages, "Domador", "🐎", "Feita para controlar criaturas selvagens.", "Animais obedecem sem questionar, exigindo respeito absoluto.", "Quem subestima se torna presa de suas próprias criações.", "Pontos fortes: Controle sobre animais, pode criar criaturas.\nPontos fracos: Vulnerável a ataques de área, dependente de animais.");
        addRelicStory(pages, "Cozinheiro", "🍲", "Nasceu do fogo das aldeias, capaz de nutrir e fortalecer.", "Alimento preparado ganha propriedades místicas.", "Comida pode envenenar se usada imprudentemente.", "Pontos fortes: Cura através de alimentos, pode envenenar inimigos.\nPontos fracos: Ineficaz em combate, passivo.");
        addRelicStory(pages, "Construtor", "🏗", "Cria mundos, blocos obedecem ao toque.", "Cidades e pontes surgem, mas carregam a intenção do portador.", "Enganos derrubam tudo em segundos, lembrando que o Nexus observa.", "Pontos fortes: Criação de blocos, construção rápida.\nPontos fracos: Ineficaz em combate, dependente de materiais.");
        addRelicStory(pages, "Abissal", "🌑", "Forjada nas profundezas, capta o medo.", "Cada passo do portador ecoa em sombras vivas.", "Quem não respeita se perde eternamente no abismo.", "Pontos fortes: Teletransporte, ataques de sombra.\nPontos fracos: Vulnerável a luz, pode causar insanidade.");
        addRelicStory(pages, "Cronosombra", "⏳", "Controla tempo e sombra, dobrando momentos.", "O portador caminha entre passado e futuro.", "Interferir demais quebra a linha temporal.", "Pontos fortes: Manipulação do tempo, ataques de sombra.\nPontos fracos: Vulnerável a luz, pode quebrar a linha temporal.");
        addRelicStory(pages, "Assassino", "🗡", "Criada para silêncio, desaparece e reaparece.", "Golpes são certeiros e invisíveis.", "Quem a usa demais é consumido pela sombra.", "Pontos fortes: Habilidades de furtividade, ataques rápidos.\nPontos fracos: Vulnerável em combate direto, pode se tornar um ser sem identidade.");
        addRelicStory(pages, "Frostis", "❄", "Forjada em gelo eterno, mantém tudo congelado.", "Aura congela pensamentos e ações.", "O frio consome quem não controla a relíquia.", "Pontos fortes: Manipulação do gelo, ataques de frio.\nPontos fracos: Vulnerável a fogo, pode congelar o próprio portador.");
        addRelicStory(pages, "Necromante", "☠", "Trás mortos à vida, mas nunca sem custo.", "Almas não descansam; gritos acompanham o portador.", "O portador caminha entre vivos e mortos constantemente.", "Pontos fortes: Invocação de mortos, controle sobre a morte.\nPontos fracos: Vulnerável a luz, pode se tornar um ser sem alma.");
        addRelicStory(pages, "Alquimista", "⚗", "Transforma materiais e cria poções antigas.", "Cada transformação cobra preço, cada poção, consequência.", "Quem não entende perde tudo que toca.", "Pontos fortes: Criação de poções e elixires, transformação de materiais.\nPontos fracos: Ineficaz em combate, dependente de materiais.");
        addRelicStory(pages, "Golem", "🪨", "Encarnado em pedra, protege e destrói.", "Paciente, inabalável; cada movimento ecoa força ancestral.", "Quem não compreende sua rigidez é esmagado por ela.", "Pontos fortes: Alta defesa, invocação de golens.\nPontos fracos: Baixa mobilidade, portador se torna um alvo.");
        addRelicStory(pages, "Dragão", "🐉", "Forjada do fogo e escamas de dragão, antiga como o mundo.", "Seu rugido reverbera por vales e montanhas.", "Portadores sentem poder absoluto, mas com responsabilidade eterna.", "Pontos fortes: Voo, ataques de fogo.\nPontos fracos: Vulnerável a água, portador pode se cansar rapidamente.");
        addRelicStory(pages, "Morte", "💀", "A Relíquia da Morte é a mais antiga de todas, nascida do primeiro fim. Ela não é má, apenas inevitável.", "Quem a empunha se torna um canal para o ciclo da vida e da morte, capaz de julgar almas e ceifar existências.", "Seu poder é absoluto, mas o preço é a própria mortalidade. O portador se torna um ser eterno, mas solitário, para sempre ligado ao fim de todas as coisas.", "Pontos fortes: Dano de vida inigualável, roubo de essência.\nPontos fracos: Depende de almas de inimigos para curar, não é eficaz contra mobs.");

        // Ranking das Relíquias (última página)
        pages.add(Component.text("§6Ranking de Poder das Relíquias\n\n" +
                "§41º - Morte\n" +
                "§b2º - Ceifador\n" +
                "§a3º - Vida\n\n" +
                "O ranking é baseado na destruição e poder em combate, mas a força de uma relíquia é tão forte quanto a determinação do seu portador."));

        meta.pages(pages);
        book.setItemMeta(meta);

        return book;
    }

    private static void addRelicStory(List<Component> pages, String name, String symbol, String page1, String page2, String page3, String page4) {
        pages.add(Component.text("§6" + symbol + " " + name + " (1/4)\n\n" + page1));
        pages.add(Component.text("§6" + symbol + " " + name + " (2/4)\n\n" + page2));
        pages.add(Component.text("§6" + symbol + " " + name + " (3/4)\n\n" + page3));
        pages.add(Component.text("§6" + symbol + " " + name + " (4/4)\n\n" + page4));
    }
}